import pandas as pd
import glob
import os
import requests


def load_and_inspect_csvs(folder_path="data/raw"):
    """Load all CSV files from the folder and print inspection details."""

    csv_files = glob.glob(os.path.join(folder_path, "*.csv"))

    # Avoid re-loading live API files generated by this script
    csv_files = [
        file for file in csv_files
        if not os.path.basename(file).startswith("live_")
    ]

    csv_files.sort()

    if not csv_files:
        print(f"No CSV files found in: {folder_path}")
        return {}

    dataframes = {}

    print("\n" + "=" * 60)
    print("LOADING LOCAL DATASETS")
    print("=" * 60)

    print(f"\nFound {len(csv_files)} local CSV files.")

    for file_path in csv_files:

        file_name = os.path.splitext(
            os.path.basename(file_path)
        )[0]

        print("\n" + "=" * 60)
        print(f"Dataset: {file_name}")
        print("=" * 60)

        try:

            df = pd.read_csv(file_path)

            dataframes[file_name] = df

            print(f"\nShape: {df.shape}")

            print("\nColumns:")
            print(df.columns.tolist())

            print("\nData types:")
            print(df.dtypes)

            print("\nFirst 5 rows:")
            print(df.head())

            print("\nMissing values per column:")
            print(df.isnull().sum())

            print(
                f"\nDuplicate rows: "
                f"{df.duplicated().sum()}"
            )

        except Exception as e:

            print(
                f"\nERROR loading {file_name}: {e}"
            )

    return dataframes



def analyze_datasets(all_data):
    """Perform consistency and validation checks."""

    print("\n" + "=" * 60)
    print("DATASET ANALYSIS")
    print("=" * 60)


    fund_master = all_data["01_fund_master"]

    print("\n--- FUND MASTER ANALYSIS ---")

    print("\nFund houses:")
    print(
        fund_master["fund_house"].unique()
    )

    print("\nCategories:")
    print(
        fund_master["category"].unique()
    )

    print("\nSub-categories:")
    print(
        fund_master["sub_category"].unique()
    )

    print("\nRisk categories:")
    print(
        fund_master["risk_category"].unique()
    )

    print("\nSEBI category codes:")
    print(
        fund_master["sebi_category_code"].unique()
    )


    print("\n" + "=" * 60)
    print("FUND MASTER vs NAV HISTORY")
    print("=" * 60)

    nav_history = all_data["02_nav_history"]

    fund_codes = set(
        fund_master["amfi_code"].dropna()
    )

    nav_codes = set(
        nav_history["amfi_code"].dropna()
    )

    missing_in_nav = (
        fund_codes - nav_codes
    )

    missing_in_master = (
        nav_codes - fund_codes
    )

    print(
        f"\nFund master schemes: "
        f"{len(fund_codes)}"
    )

    print(
        f"NAV history schemes: "
        f"{len(nav_codes)}"
    )

    print(
        "\nSchemes in fund_master "
        "but missing NAV history:"
    )

    print(missing_in_nav)

    print(
        "\nSchemes with NAV history "
        "but missing from fund_master:"
    )

    print(missing_in_master)


    print("\n" + "=" * 60)
    print("NAV HISTORY COVERAGE")
    print("=" * 60)

    rows_per_scheme = (
        nav_history
        .groupby("amfi_code")
        .size()
    )

    print(
        "\nNAV records per scheme statistics:"
    )

    print(
        rows_per_scheme.describe()
    )

    median_rows = (
        rows_per_scheme.median()
    )

    low_history_schemes = (
        rows_per_scheme[
            rows_per_scheme
            < median_rows * 0.5
        ]
    )

    print(
        "\nSchemes with unusually "
        "little NAV history:"
    )

    if low_history_schemes.empty:

        print("None")

    else:

        print(low_history_schemes)

    print("\n" + "=" * 60)
    print("INVESTOR TRANSACTION VALIDATION")
    print("=" * 60)

    investor_txns = (
        all_data[
            "08_investor_transactions"
        ]
    )

    txn_codes = set(
        investor_txns[
            "amfi_code"
        ].dropna()
    )

    transactions_not_in_master = (
        txn_codes - fund_codes
    )

    print(
        "\nTransaction schemes "
        "not in fund_master:"
    )

    print(
        transactions_not_in_master
    )

    if len(
        transactions_not_in_master
    ) == 0:

        print(
            "All transaction scheme codes "
            "exist in fund_master."
        )



def fetch_nav(scheme_code):
    """Fetch full NAV history for a scheme from mfapi.in."""

    url = (
        f"https://api.mfapi.in/mf/"
        f"{scheme_code}"
    )

    response = requests.get(
        url,
        timeout=30
    )

    response.raise_for_status()

    data = response.json()

    if "meta" not in data or "data" not in data:
        raise ValueError(
            f"Unexpected API response for "
            f"scheme {scheme_code}"
        )

    return data


def search_scheme(query):
    """Search MFAPI for a mutual fund scheme."""

    url = "https://api.mfapi.in/mf/search"

    response = requests.get(
        url,
        params={"q": query},
        timeout=30
    )

    response.raise_for_status()

    return response.json()



def search_hdfc_top_100():

    print("\n" + "=" * 60)
    print("SEARCHING FOR HDFC TOP 100")
    print("=" * 60)

    try:

        results = search_scheme(
            "HDFC Top 100"
        )

        if not results:

            print(
                "No search results found."
            )

            return

        print(
            f"\nFound {len(results)} results:\n"
        )

        for result in results:

            print(
                result.get("schemeCode"),
                "-",
                result.get("schemeName")
            )

    except requests.RequestException as e:

        print(
            f"API search error: {e}"
        )

    except Exception as e:

        print(
            f"Search error: {e}"
        )



def fetch_live_nav_data():

    print("\n" + "=" * 60)
    print("LIVE NAV DATA FETCH")
    print("=" * 60)

    os.makedirs(
        "data/raw",
        exist_ok=True
    )


    hdfc_code = 125497

    print(
        "\nFetching HDFC Top 100 Direct..."
    )

    try:

        hdfc_data = fetch_nav(
            hdfc_code
        )

        scheme_name = (
            hdfc_data["meta"]
            .get("scheme_name", "")
        )

        fund_house = (
            hdfc_data["meta"]
            .get("fund_house", "")
        )

        # Verify correct scheme
        assert "HDFC" in scheme_name.upper(), (
            f"Expected HDFC scheme, "
            f"got: {scheme_name}"
        )

        print(
            "Scheme:",
            scheme_name
        )

        print(
            "Fund house:",
            fund_house
        )

        hdfc_df = pd.DataFrame(
            hdfc_data["data"]
        )

        hdfc_df.to_csv(
            "data/raw/"
            "live_HDFC_Top_100_nav.csv",
            index=False
        )

        print(
            f"Saved {len(hdfc_df)} "
            "rows for HDFC Top 100."
        )

    except Exception as e:

        print(
            f"ERROR fetching "
            f"HDFC Top 100: {e}"
        )


    key_schemes = {

        "SBI_Bluechip":
            119551,

        "ICICI_Bluechip":
            120503,

        "Nippon_Large_Cap":
            118632,

        "Axis_Bluechip":
            119092,

        "Kotak_Bluechip":
            120841,
    }

    print("\n" + "-" * 60)
    print("FETCHING KEY SCHEMES")
    print("-" * 60)

    for name, code in key_schemes.items():

        print(
            f"\nFetching {name} "
            f"({code})..."
        )

        try:

            data = fetch_nav(code)

            scheme_name = (
                data["meta"]
                .get("scheme_name", "")
            )

            print(
                "API Scheme:",
                scheme_name
            )

            df = pd.DataFrame(
                data["data"]
            )

            output_file = (
                f"data/raw/"
                f"live_{name}_nav.csv"
            )

            df.to_csv(
                output_file,
                index=False
            )

            print(
                f"Saved {len(df)} "
                f"rows for {name}."
            )

        except requests.RequestException as e:

            print(
                f"API ERROR for "
                f"{name}: {e}"
            )

        except Exception as e:

            print(
                f"ERROR processing "
                f"{name}: {e}"
            )

    print("\n" + "=" * 60)
    print(
        "LIVE NAV FETCH COMPLETE"
    )
    print("=" * 60)


if __name__ == "__main__":

    # ----------------------------------
    # Load original CSV datasets
    # ----------------------------------

    all_data = (
        load_and_inspect_csvs()
    )

    print("\n" + "=" * 60)
    print("DATA INGESTION SUMMARY")
    print("=" * 60)

    print(
        f"Total datasets loaded: "
        f"{len(all_data)}"
    )

    print(
        f"Dataset names: "
        f"{list(all_data.keys())}"
    )



    if all_data:

        try:

            analyze_datasets(
                all_data
            )

        except KeyError as e:

            print(
                f"\nAnalysis KeyError: {e}"
            )

            print(
                "Check whether the required "
                "column/dataset name exists."
            )



    search_hdfc_top_100()



    fetch_live_nav_data()